### ISSUE TITLE
What happened to the old repo?

### ISSUE THREAD

**Issue by outpoints** [cademtz/Sparkly-Rewrite-UI#1]
https://github.com/cademtz/Dumpster-Fire ?

**Comment by cademtz** [comment]
We had an issue with a paster. Typically it's not that bad, but he was claiming Dumpster Fire as his own, right in front of us. He is also selling other programs that aren't made by him, but rather from other open sources like ours. He even has a website for it (See https://www.FaggoCheat.org).

So have we decided it would be safer to only release compiled versions to prevent more scams. We are making a new private git repo to hide the source.

**Comment by outpoints** [comment]
Damnit!
Can you add me to the private git repo?
Or give me your Discord at least?

**Comment by outpoints** [comment]
Or you can add me!
Night#0001

**Comment by cademtz** [comment]
The Dumpster Fire project Discord can be found here: https://www.discord.gg/zhQV4v4
