### ISSUE TITLE
Really? Video game cheats?

### ISSUE THREAD

**Issue by IAmWolfie** [cademtz/Sparkly-Rewrite-UI#4]
Cheating in video games isn't funny. It hurts a lot of peoples feelings. You should be mature and reevaluate your use of your programming talent. Personally I just like to kiss guys,

**Comment by mememasterlord32345** [comment]
i agree completly honestly...

**Comment by IAmWolfie** [comment]
> i agree completly honestly...

Shut it, cracker.

**Comment by mememasterlord32345** [comment]
> > i agree completly honestly...
> 
> Shut it, cracker.

wtf dude i agred tho

**Comment by cademtz** [comment]
closed because there's 0 sense in u iggas

**Comment by IAmWolfie** [comment]
> > > i agree completly honestly...
> > 
> > 
> > Shut it, cracker.
> 
> wtf dude i agred tho

Agreed what? What are you referencing? Are you insane?

**Comment by cademtz** [comment]
I SAID CLOSED

**Comment by IAmWolfie** [comment]
> closed because there's 0 sense in u iggas

Really? The n-word too? God, you sure are immature.

**Comment by cademtz** [comment]
SHUT UP
