### ISSUE TITLE
Nice rage delete.

### ISSUE THREAD

**Issue by IAmWolfie** [cademtz/Sparkly-Rewrite-UI#5]
Just cracked you and your mom's hacks. Also got your newborn brother's stuff too. Leak tomorrow on UnknownCheats. Cya, noob.

**Comment by cademtz** [comment]
joe mamma gay above my name

**Comment by mememasterlord32345** [comment]
lol ikr

**Comment by IAmWolfie** [comment]
> joe mamma gay above my name

What the F

**Comment by IAmWolfie** [comment]
**Stop.**
